name: GCP Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: "actions/checkout@v4"

        # Authenticate with Google Cloud
      - id: "auth"
        uses: "google-github-actions/auth@v2.0.0"
        with:
          workload_identity_provider: ${{secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      # Setup pnpm
      - name: pnpm-setup
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Setup taskfile
      - name: Setup taskfile
        run: |
          sudo snap install task --classic

      - name: Install Dependencies
        run: task install

      - name: Run Tests
        run: task test

      - name: Terraform Plan
        run: task terraform:plan

      - name: Terraform Apply
        run: task terraform:apply
